add_newline = true

[git_commit]
commit_hash_length = 4
tag_symbol = "ðŸ”– "

[directory]
style = "bold #2e7de9"
truncation_length = 8

[java]
disabled = false
detect_extensions = ["java", "class", "gradle", "cljs", "cljc"]
[jobs]
disabled = false

[battery]
disabled = true

[aws]
disabled = true

[azure]
disabled = true
