
[terminal.shell]
args = ["-l", "-c", "tmux attach || tmux"]
program = "/bin/zsh"

[font]
size = 10
offset = { x = 0, y = 0 }
[font.normal]
family = "Rec Mono Duotone Symbols"

[env]
term = "xterm-256color"

[selection]
save_to_clipboard = true

[keyboard]
bindings = [
	# delete previous word using ctrl+backspace (binded to ctrl+w which is the default key for that)
	{ key = "Back", mods = "Control", chars = "\u0017" }
]

[general]
import = [
	"~/.config/alacritty/theme.toml"
]
