
[terminal.shell]
args = ["-l", "-c", "tmux attach || tmux"]
program = "/bin/zsh"

[font]
size = 10
offset = { x = 0, y = 0 }
[font.normal]
family = "JetBrainsMono Nerd Font"

[env]
term = "xterm-256color"

[selection]
save_to_clipboard = true

[general]
import = [
	"~/.config/alacritty/auto-theme/theme.toml"
]
